services:
  # Frontend React/Vite Application
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8087:8087"
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_GITHUB_CLIENT_ID=${VITE_GITHUB_CLIENT_ID}
      - VITE_BYPASS_AUTH=true
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  # Backend FastAPI Service - Unified Multi-Agent System
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # Legacy environment variables (for backward compatibility)
      - OPENAI_API_KEY=${OPENAI_API_KEY}

              - GITHUB_CLIENT_SECRET=${VITE_GITHUB_CLIENT_SECRET}
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEMO_MODE=${DEMO_MODE:-true}
      
      # Unified System Configuration
      - ENABLE_API_DOCS=${ENABLE_API_DOCS:-true}
      - API_PREFIX=${API_PREFIX:-/api}
      
      # LLM Configuration
      - DEFAULT_LLM_PROVIDER=${DEFAULT_LLM_PROVIDER:-openai}
      - DEFAULT_LLM_MODEL=${DEFAULT_LLM_MODEL:-gpt-4o}
      - VISION_MODEL=${VISION_MODEL:-gpt-4o}
      - CHEAP_MODEL=${CHEAP_MODEL:-gpt-4o-mini}
      - LLM_TEMPERATURE=${LLM_TEMPERATURE:-0.1}
      - LLM_MAX_TOKENS=${LLM_MAX_TOKENS:-4000}
      - LLM_TIMEOUT=${LLM_TIMEOUT:-30}
      
      # Agent Configuration
      - AGENT_MAX_RETRIES=${AGENT_MAX_RETRIES:-3}
      - AGENT_TIMEOUT=${AGENT_TIMEOUT:-60}
      - AGENT_MEMORY_LIMIT=${AGENT_MEMORY_LIMIT:-50}
      - USE_CHEAPER_MODELS=${USE_CHEAPER_MODELS:-true}
      - VISION_ENABLED=${VISION_ENABLED:-true}
      
      # Browser Automation
      - USE_BROWSER_AUTOMATION=${USE_BROWSER_AUTOMATION:-true}
      - BROWSER_HEADLESS=${BROWSER_HEADLESS:-true}
      - BROWSER_TIMEOUT=${BROWSER_TIMEOUT:-30000}
      - MAX_BROWSER_INSTANCES=${MAX_BROWSER_INSTANCES:-3}
      - SAVE_SCREENSHOTS=${SAVE_SCREENSHOTS:-false}
      
      # Workflow Settings
      - MAX_CONCURRENT_AGENTS=${MAX_CONCURRENT_AGENTS:-5}
      - DEFAULT_MAX_EXECUTION_TIME=${DEFAULT_MAX_EXECUTION_TIME:-300}
      - DEFAULT_MAX_PAGES_PER_SITE=${DEFAULT_MAX_PAGES_PER_SITE:-10}
      - ENABLE_PARALLEL_PROCESSING=${ENABLE_PARALLEL_PROCESSING:-true}
      - MAX_CONCURRENT_COMPANIES=${MAX_CONCURRENT_COMPANIES:-3}
      - CACHE_TTL_SECONDS=${CACHE_TTL_SECONDS:-3600}
      - ENABLE_METRICS=${ENABLE_METRICS:-true}
      
      # Logging
      - ENABLE_CONSOLE_LOGGING=${ENABLE_CONSOLE_LOGGING:-true}
      - LOG_FILE_PATH=${LOG_FILE_PATH:-/app/logs/system.log}
    
    volumes:
      - ./backend/logs:/app/logs
      - ./screenshots:/app/screenshots
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: uv run python start.py

networks:
  app-network:
    driver: bridge