// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;
const BYPASS_AUTH = import.meta.env.VITE_BYPASS_AUTH === 'true';

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing Supabase environment variables. Please check your .env file for VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  db: {
    schema: 'public'
  },
  auth: {
    persistSession: true,
    storageKey: 'supabase.auth.token',
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});

// Note: Service role client has been removed from frontend for security.
// Service role operations should be performed on the backend only.
// For development bypass, use regular client with appropriate RLS policies.

if (import.meta.env.DEV && BYPASS_AUTH) {
  console.log('Development mode: Auth bypass enabled');
}

// Export null for backwards compatibility - service role operations moved to backend
export const supabaseServiceRole = null;