// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://scvqgfkslffykgtnvrdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjdnFnZmtzbGZmeWtndG52cmRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5ODQ2NDcsImV4cCI6MjA2MzU2MDY0N30.X2uxWQVigQRMU9UAAoy3rW4syaetxDC8ZROX1iGKCF0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);